### ISSUE TITLE
Error at Homebridge startup

### ISSUE THREAD

**Issue by DanieleBarreca** [vniehues/homebridge-saphi-tv#20]
After restarting homebridge, I get the following error:

[1/22/2022, 10:23:54 AM] ERROR LOADING PLUGIN homebridge-saphi-tv:
[1/22/2022, 10:23:54 AM] Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/local/lib/node_modules/homebridge-saphi-tv/node_modules/node-fetch/src/index.js from /usr/local/lib/node_modules/homebridge-saphi-tv/node_modules/fetch-timeout/src/index.js not supported.
Instead change the require of /usr/local/lib/node_modules/homebridge-saphi-tv/node_modules/node-fetch/src/index.js in /usr/local/lib/node_modules/homebridge-saphi-tv/node_modules/fetch-timeout/src/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-saphi-tv/node_modules/fetch-timeout/src/index.js:6:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-saphi-tv/dist/utilities.js:8:41)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-saphi-tv/dist/platform.js:7:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-saphi-tv/dist/index.js:3:20)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:135:108)
    at PluginManager.initializeInstalledPlugins (/usr/local/lib/node_modules/homebridge/lib/pluginManager.js:64:30)
    at async Server.start (/usr/local/lib/node_modules/homebridge/lib/server.js:106:9)

Versions:
Homebridge v1.4.0 (HAP v0.10.0) (Homebridge 8062) 
Node v17.4.0
Npm 8.3.1

**Comment by vniehues** [comment]
Hey @DanieleBarreca :) 
Thanks for opening this issue. I'll have a look at that error later today and will report my findings (and hopefully a fix) in here.

**Comment by vniehues** [comment]
Fixed in [v1.0.3](https://github.com/vniehues/homebridge-saphi-tv/releases/tag/v1.0.3).
Thank you for reporting the issue!
